/*
 * POC app API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The Movie model module.
 * @module model/Movie
 * @version 1.0.0
 */
export class Movie {
  /**
   * Constructs a new <code>Movie</code>.
   * @alias module:model/Movie
   * @class
   * @param name {String} 
   * @param rating {module:model/Movie.RatingEnum} 
   * @param genre {module:model/Movie.GenreEnum} 
   */
  constructor(name, rating, genre) {
    this.name = name;
    this.rating = rating;
    this.genre = genre;
  }

  /**
   * Constructs a <code>Movie</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Movie} obj Optional instance to populate.
   * @return {module:model/Movie} The populated <code>Movie</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Movie();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('rating'))
        obj.rating = ApiClient.convertToType(data['rating'], 'String');
      if (data.hasOwnProperty('synopsis'))
        obj.synopsis = ApiClient.convertToType(data['synopsis'], 'String');
      if (data.hasOwnProperty('genre'))
        obj.genre = ApiClient.convertToType(data['genre'], 'String');
      if (data.hasOwnProperty('release_date'))
        obj.releaseDate = ApiClient.convertToType(data['release_date'], 'Date');
      if (data.hasOwnProperty('user'))
        obj.user = ApiClient.convertToType(data['user'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
Movie.prototype.id = undefined;

/**
 * @member {String} name
 */
Movie.prototype.name = undefined;

/**
 * Allowed values for the <code>rating</code> property.
 * @enum {String}
 * @readonly
 */
Movie.RatingEnum = {
  /**
   * value: "G"
   * @const
   */
  G: "G",

  /**
   * value: "PG"
   * @const
   */
  PG: "PG",

  /**
   * value: "PG-13"
   * @const
   */
  pG13: "PG-13",

  /**
   * value: "R"
   * @const
   */
  R: "R",

  /**
   * value: "NC-17"
   * @const
   */
  nC17: "NC-17"
};
/**
 * @member {module:model/Movie.RatingEnum} rating
 */
Movie.prototype.rating = undefined;

/**
 * @member {String} synopsis
 */
Movie.prototype.synopsis = undefined;

/**
 * Allowed values for the <code>genre</code> property.
 * @enum {String}
 * @readonly
 */
Movie.GenreEnum = {
  /**
   * value: "Action"
   * @const
   */
  action: "Action",

  /**
   * value: "Comedy"
   * @const
   */
  comedy: "Comedy",

  /**
   * value: "Drama"
   * @const
   */
  drama: "Drama",

  /**
   * value: "Sci-fi"
   * @const
   */
  sciFi: "Sci-fi",

  /**
   * value: "Horror"
   * @const
   */
  horror: "Horror",

  /**
   * value: "Mystery"
   * @const
   */
  mystery: "Mystery",

  /**
   * value: "Romance"
   * @const
   */
  romance: "Romance",

  /**
   * value: "Thriller"
   * @const
   */
  thriller: "Thriller",

  /**
   * value: "Western"
   * @const
   */
  western: "Western",

  /**
   * value: "Animation"
   * @const
   */
  animation: "Animation"
};
/**
 * @member {module:model/Movie.GenreEnum} genre
 */
Movie.prototype.genre = undefined;

/**
 * @member {Date} releaseDate
 */
Movie.prototype.releaseDate = undefined;

/**
 * @member {Number} user
 */
Movie.prototype.user = undefined;

